//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDLMLab {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PosledneParametreMerania : global::System.Configuration.ApplicationSettingsBase {
        
        private static PosledneParametreMerania defaultInstance = ((PosledneParametreMerania)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PosledneParametreMerania())));
        
        public static PosledneParametreMerania Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double eStartPoint {
            get {
                return ((double)(this["eStartPoint"]));
            }
            set {
                this["eStartPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double eEndPoint {
            get {
                return ((double)(this["eEndPoint"]));
            }
            set {
                this["eEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double eStepTime {
            get {
                return ((double)(this["eStepTime"]));
            }
            set {
                this["eStepTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double eResolution {
            get {
                return ((double)(this["eResolution"]));
            }
            set {
                this["eResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ePocetKrokov {
            get {
                return ((int)(this["ePocetKrokov"]));
            }
            set {
                this["ePocetKrokov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eKonstanta {
            get {
                return ((int)(this["eKonstanta"]));
            }
            set {
                this["eKonstanta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mStart {
            get {
                return ((int)(this["mStart"]));
            }
            set {
                this["mStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mEnd {
            get {
                return ((int)(this["mEnd"]));
            }
            set {
                this["mEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double mResolution {
            get {
                return ((double)(this["mResolution"]));
            }
            set {
                this["mResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double mKonstanta {
            get {
                return ((double)(this["mKonstanta"]));
            }
            set {
                this["mKonstanta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mDensOfMeas {
            get {
                return ((int)(this["mDensOfMeas"]));
            }
            set {
                this["mDensOfMeas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double e2DStartPoint {
            get {
                return ((double)(this["e2DStartPoint"]));
            }
            set {
                this["e2DStartPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double e2DEndPoint {
            get {
                return ((double)(this["e2DEndPoint"]));
            }
            set {
                this["e2DEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double e2DStepTime {
            get {
                return ((double)(this["e2DStepTime"]));
            }
            set {
                this["e2DStepTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int e2DPocetKrokov {
            get {
                return ((int)(this["e2DPocetKrokov"]));
            }
            set {
                this["e2DPocetKrokov"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int m2DStartPoint {
            get {
                return ((int)(this["m2DStartPoint"]));
            }
            set {
                this["m2DStartPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int m2DEndPoint {
            get {
                return ((int)(this["m2DEndPoint"]));
            }
            set {
                this["m2DEndPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double m2DResolution {
            get {
                return ((double)(this["m2DResolution"]));
            }
            set {
                this["m2DResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int m2DDensOfMeas {
            get {
                return ((int)(this["m2DDensOfMeas"]));
            }
            set {
                this["m2DDensOfMeas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double m2DTimePerAmu {
            get {
                return ((double)(this["m2DTimePerAmu"]));
            }
            set {
                this["m2DTimePerAmu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double mTimePerAmu {
            get {
                return ((double)(this["mTimePerAmu"]));
            }
            set {
                this["mTimePerAmu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nameBox {
            get {
                return ((string)(this["nameBox"]));
            }
            set {
                this["nameBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string noteBox {
            get {
                return ((string)(this["noteBox"]));
            }
            set {
                this["noteBox"] = value;
            }
        }
    }
}
